### PR TITLE
remove vendor directory

### PR DESCRIPTION
**Pull request by urandom2**
- built on #14
- modules supersede vendor directories: [see wiki](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away)
  - this is not required, but does clean-up the repo, thus it is a separate pr
  - may be better to wait till 1.13 drops and the default is to ignore vendor

### CODE REVIEW

**Comment by urandom2** [comment]
@valyala, sorry to pester, but do you have interest in removing the vendor directory at this time, or would you rather leave it in place for now?

**Comment by urandom2** [comment]
@valyala, thought I would bump one last time before leaving this to rot (or closing it out).

**Comment by valyala** [comment]
@arnottcr , let's wait for go1.13 and then remove the `vendor` directory

**Comment by urandom2** [comment]
bumping, since it is now after the go1.13 release

**Comment by valyala** [comment]
Merged the PR. Thanks, @arnottcr !

**Comment by valyala** [comment]
Published `v1.1.0` tag with the given PR included.

**Pull request merged**
